#pragma once

#define NET_ERROR					(std::numeric_limits<std::size_t>::max)()
#define NET_GOOD					0
#define NET_UNKNOWN					1
#define NET_NOT_READY				2
#define NET_NOT_SUPPORTED			3
#define NET_BLOCKING_OPERATION		4
#define NET_LIMIT					5
#define NET_FAULT					6
#define NET_TRY_AGAIN				7
#define NET_INVAL_ARG				8
#define NET_NO_RECOVERY				9
#define NET_AF_NO_SUPPORT			10
#define NET_NOT_ENOUGH_MEMORY		11
#define NET_HOST_NOT_FOUND			12
#define NET_TYPE_NOT_FOUND			13
#define NET_SOCK_TYPE_NO_SUPPORT	14
#define NET_NO_DATA					15
#define NET_NOT_INIT				16
#define NET_ADDR_IN_USE				17
#define NET_OP_INTR					18
#define NET_ALREADY					19
#define NET_ADDR_NOT_AVAIL			20
#define NET_CONN_REFUSED			21
#define NET_IS_CONN					22
#define NET_NET_UNREACH				23
#define NET_HOST_UNREACH			24
#define NET_NO_BUFS					25
#define NET_NOT_SOCK				26
#define NET_TIMEDOUT				27
#define NET_WOULD_BLOCK				28
#define NET_NO_ACCES				29
#define NET_TOO_MANY_SOCK			30
#define NET_INVALID_PROVIDER		31
#define NET_INVALID_PROCTABLE		32
#define NET_PROTO_NO_SUPPORT		33
#define NET_WRONG_PROTO_TYPE		34
#define NET_PROVIDER_INIT_FAILED	35
#define NET_NOT_CONNECTED			36
#define NET_RESET					37
#define NET_OP_NOT_SUPPORTED		38
#define NET_SHUTDOWN				39
#define NET_TOO_LONG				40
#define NET_CONN_ABORTED			41
#define NET_CONN_RESET				42